package com.mycompany.calculatorgui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Prime
 */
public class gui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gui.class.getName());
    private CalculatorLogic logic = new CalculatorLogic();
    
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
//        textBox.setEditable(false);
        textBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            textBoxKeyTyped(evt);
            }
        });
    }
    
    private void textBoxKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        // Allow digits, backspace, and the decimal point
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE || c == '.')) {
            evt.consume(); // Block the character
        }

        // Prevent multiple decimal points
        if (c == '.' && textBox.getText().contains(".")) {
            evt.consume();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textBox = new javax.swing.JTextField();
        calculatorTitle = new javax.swing.JLabel();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        BtnDiv = new javax.swing.JButton();
        BtnMult = new javax.swing.JButton();
        BtnMin = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        bDot = new javax.swing.JButton();
        bEquals = new javax.swing.JButton();
        BtnPlus = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));

        textBox.setBackground(new java.awt.Color(255, 255, 255));
        textBox.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        calculatorTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculatorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculatorTitle.setText("Calculator (Melocoton)");
        calculatorTitle.setToolTipText("");
        calculatorTitle.setFocusTraversalPolicyProvider(true);

        b9.setBackground(new java.awt.Color(255, 255, 0));
        b9.setForeground(new java.awt.Color(0, 0, 0));
        b9.setText("9");
        b9.addActionListener(this::b9ActionPerformed);

        b7.setBackground(new java.awt.Color(255, 255, 0));
        b7.setForeground(new java.awt.Color(0, 0, 0));
        b7.setText("7");
        b7.addActionListener(this::b7ActionPerformed);

        b8.setBackground(new java.awt.Color(255, 255, 0));
        b8.setForeground(new java.awt.Color(0, 0, 0));
        b8.setText("8");
        b8.addActionListener(this::b8ActionPerformed);

        b4.setBackground(new java.awt.Color(255, 255, 0));
        b4.setForeground(new java.awt.Color(0, 0, 0));
        b4.setText("4");
        b4.addActionListener(this::b4ActionPerformed);

        b5.setBackground(new java.awt.Color(255, 255, 0));
        b5.setForeground(new java.awt.Color(0, 0, 0));
        b5.setText("5");
        b5.addActionListener(this::b5ActionPerformed);

        b6.setBackground(new java.awt.Color(255, 255, 0));
        b6.setForeground(new java.awt.Color(0, 0, 0));
        b6.setText("6");
        b6.addActionListener(this::b6ActionPerformed);

        b2.setBackground(new java.awt.Color(255, 255, 0));
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setText("2");
        b2.addActionListener(this::b2ActionPerformed);

        b1.setBackground(new java.awt.Color(255, 255, 0));
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setText("1");
        b1.addActionListener(this::b1ActionPerformed);

        b3.setBackground(new java.awt.Color(255, 255, 0));
        b3.setForeground(new java.awt.Color(0, 0, 0));
        b3.setText("3");
        b3.addActionListener(this::b3ActionPerformed);

        BtnDiv.setText("/");
        BtnDiv.addActionListener(this::BtnDivActionPerformed);

        BtnMult.setText("*");
        BtnMult.addActionListener(this::BtnMultActionPerformed);

        BtnMin.setText("-");
        BtnMin.addActionListener(this::BtnMinActionPerformed);

        BtnClear.setBackground(new java.awt.Color(255, 0, 0));
        BtnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(this::BtnClearActionPerformed);

        bDot.setBackground(new java.awt.Color(0, 0, 0));
        bDot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bDot.setForeground(new java.awt.Color(255, 255, 0));
        bDot.setText(".");
        bDot.addActionListener(this::bDotActionPerformed);

        bEquals.setBackground(new java.awt.Color(255, 0, 0));
        bEquals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bEquals.setText("=");
        bEquals.addActionListener(this::bEqualsActionPerformed);

        BtnPlus.setText("+");
        BtnPlus.addActionListener(this::BtnPlusActionPerformed);

        b0.setBackground(new java.awt.Color(255, 255, 0));
        b0.setForeground(new java.awt.Color(0, 0, 0));
        b0.setText("0");
        b0.addActionListener(this::b0ActionPerformed);

        BtnBack.setBackground(new java.awt.Color(51, 51, 51));
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(this::BtnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(textBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(calculatorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calculatorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        textBox.setText(textBox.getText() + "4");
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        textBox.setText(textBox.getText() + "5");
    }//GEN-LAST:event_b5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        textBox.setText(textBox.getText() + "1");
    }//GEN-LAST:event_b1ActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        textBox.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        textBox.setText(textBox.getText() + "0");
    }//GEN-LAST:event_b0ActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        String str = textBox.getText();
        if (str.length() > 0) {
            textBox.setText(str.substring(0, str.length() - 1));
        }
    }//GEN-LAST:event_BtnBackActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        textBox.setText(textBox.getText() + "7");
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        textBox.setText(textBox.getText() + "8");
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        textBox.setText(textBox.getText() + "9");
    }//GEN-LAST:event_b9ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        textBox.setText(textBox.getText() + "6");
    }//GEN-LAST:event_b6ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        textBox.setText(textBox.getText() + "2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        textBox.setText(textBox.getText() + "3");
    }//GEN-LAST:event_b3ActionPerformed

    private void bDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDotActionPerformed
        textBox.setText(textBox.getText() + ".");
    }//GEN-LAST:event_bDotActionPerformed

    private void BtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlusActionPerformed
        try {
            double val = Double.parseDouble(textBox.getText());
                logic.setFirstOperand(val, "+");
            textBox.setText(""); // Clear for the next number
        } catch (NumberFormatException e) {
            // Do nothing if box is empty or invalid
        }
    }//GEN-LAST:event_BtnPlusActionPerformed

    private void BtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivActionPerformed
        try {
            double val = Double.parseDouble(textBox.getText());
            logic.setFirstOperand(val, "/");
            textBox.setText(""); // Clear for the next number
        } catch (NumberFormatException e) {
            // Do nothing if box is empty or invalid
        }
        
//        num1 = Double.parseDouble(textBox.getText());
//        textBox.setText("");
//        operator="/";
    }//GEN-LAST:event_BtnDivActionPerformed

    private void BtnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinActionPerformed
        try {
            double val = Double.parseDouble(textBox.getText());
            logic.setFirstOperand(val, "-");
            textBox.setText(""); // Clear for the next number
        } catch (NumberFormatException e) {
            // Do nothing if box is empty or invalid
        }
        
//        num1 = Double.parseDouble(textBox.getText());
//        textBox.setText("");
//        operator="-";
    }//GEN-LAST:event_BtnMinActionPerformed

    private void BtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultActionPerformed
        try {
            double val = Double.parseDouble(textBox.getText());
            logic.setFirstOperand(val, "*");
            textBox.setText(""); // Clear for the next number
        } catch (NumberFormatException e) {
            // Do nothing if box is empty or invalid
        }
        
//        num1 = Double.parseDouble(textBox.getText());
//        textBox.setText("");
//        operator="*";
    }//GEN-LAST:event_BtnMultActionPerformed

    private void bEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqualsActionPerformed
        try {
            double secondNum = Double.parseDouble(textBox.getText());
            logic.calculate(secondNum);
            textBox.setText(logic.getFormattedResult());
        } catch (ArithmeticException e) {
            textBox.setText("Error: Div by 0");
        } catch (NumberFormatException e) {
            // Handle case where equals is pressed without a second number
        }


//        try {
//            // Validation: Check if the text box is empty before parsing
//            if (textBox.getText().isEmpty()) return;
//
//            num2 = Double.parseDouble(textBox.getText());
//
//            logic.calculate(num1, num2, operator);
//            textBox.setText(logic.getFormattedResult());
//
//            operator = null;
//        } catch (ArithmeticException e) {
//            // Handle division by zero
//            textBox.setText("Error: Div by 0");
//        } catch (NumberFormatException e) {
//            // Handle cases where the input is just a decimal point or invalid
//            textBox.setText("Invalid Input");
//        }
    }//GEN-LAST:event_bEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDiv;
    private javax.swing.JButton BtnMin;
    private javax.swing.JButton BtnMult;
    private javax.swing.JButton BtnPlus;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bDot;
    private javax.swing.JButton bEquals;
    private javax.swing.JLabel calculatorTitle;
    private javax.swing.JTextField textBox;
    // End of variables declaration//GEN-END:variables
}
